### ISSUE TITLE
What command line do you use to run this "sandbag-abm3-example"?

### ISSUE THREAD

**Issue by siweih1997** [ActivitySim/sandag-abm3-example#26]
Hi Jeffrey and Sijia,

This is Siwei Hu, a PhD student from University of California, Irvine.

I am wondering: what command line do you use to run this "sandag-abm3-example model"? I use the following command with the latest activitysim (1.3.2):

activitysim run -c configs/common -c configs/resident -d data -o output -s settings_mp.yaml --ext extensions

But it has some KeyError on "update tables" as follows:

<img width="1112" alt="Screenshot 2024-09-19 at 1 07 12 PM" src="https://github.com/user-attachments/assets/5b2bad7b-75fb-4208-89c7-bc2d73f97dab">

So we are wondeing: since there is not too much documentation on the github page, what is the correct command line to run this example?

**Comment by jpn--** [comment]
You've got the correct command 😄.  We just needed to fix a bug left in the `settings_mp.yaml` file, which referred to the non-existent (at least in this repo + standard ActivitySim) `update_tables` step.

I've copied your command to the README page for this repo as well.  Thanks for inquiring.
